//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supportsapi.labgenomics.com.ServiceSMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.tongkni.co.kr/", ConfigurationName="ServiceSMS.ServiceSMSSoap")]
    public interface ServiceSMSSoap {
        
        // CODEGEN: http://webservice.tongkni.co.kr/ 네임스페이스의 요소 이름 smsID이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/SendSMS", ReplyAction="*")]
        supportsapi.labgenomics.com.ServiceSMS.SendSMSResponse SendSMS(supportsapi.labgenomics.com.ServiceSMS.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.SendSMSResponse> SendSMSAsync(supportsapi.labgenomics.com.ServiceSMS.SendSMSRequest request);
        
        // CODEGEN: http://webservice.tongkni.co.kr/ 네임스페이스의 요소 이름 smsID이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/SendSMSReserve", ReplyAction="*")]
        supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveResponse SendSMSReserve(supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/SendSMSReserve", ReplyAction="*")]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveResponse> SendSMSReserveAsync(supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveRequest request);
        
        // CODEGEN: http://webservice.tongkni.co.kr/ 네임스페이스의 요소 이름 smsID이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/SendSMSCallBack", ReplyAction="*")]
        supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackResponse SendSMSCallBack(supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/SendSMSCallBack", ReplyAction="*")]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackResponse> SendSMSCallBackAsync(supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackRequest request);
        
        // CODEGEN: http://webservice.tongkni.co.kr/ 네임스페이스의 요소 이름 smsID이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/SendSMSCallBackReserve", ReplyAction="*")]
        supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveResponse SendSMSCallBackReserve(supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/SendSMSCallBackReserve", ReplyAction="*")]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveResponse> SendSMSCallBackReserveAsync(supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveRequest request);
        
        // CODEGEN: http://webservice.tongkni.co.kr/ 네임스페이스의 요소 이름 smsID이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/ReserveCancle", ReplyAction="*")]
        supportsapi.labgenomics.com.ServiceSMS.ReserveCancleResponse ReserveCancle(supportsapi.labgenomics.com.ServiceSMS.ReserveCancleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/ReserveCancle", ReplyAction="*")]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.ReserveCancleResponse> ReserveCancleAsync(supportsapi.labgenomics.com.ServiceSMS.ReserveCancleRequest request);
        
        // CODEGEN: http://webservice.tongkni.co.kr/ 네임스페이스의 요소 이름 smsID이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/GetRemainCount", ReplyAction="*")]
        supportsapi.labgenomics.com.ServiceSMS.GetRemainCountResponse GetRemainCount(supportsapi.labgenomics.com.ServiceSMS.GetRemainCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/GetRemainCount", ReplyAction="*")]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.GetRemainCountResponse> GetRemainCountAsync(supportsapi.labgenomics.com.ServiceSMS.GetRemainCountRequest request);
        
        // CODEGEN: http://webservice.tongkni.co.kr/ 네임스페이스의 요소 이름 smsID이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/GetWeeklyLimit", ReplyAction="*")]
        supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitResponse GetWeeklyLimit(supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tongkni.co.kr/GetWeeklyLimit", ReplyAction="*")]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitResponse> GetWeeklyLimitAsync(supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(supportsapi.labgenomics.com.ServiceSMS.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hashValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senderPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string receivePhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string smsContent;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(string smsID, string hashValue, string senderPhone, string receivePhone, string smsContent) {
            this.smsID = smsID;
            this.hashValue = hashValue;
            this.senderPhone = senderPhone;
            this.receivePhone = receivePhone;
            this.smsContent = smsContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(supportsapi.labgenomics.com.ServiceSMS.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(string SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSReserveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSReserve", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveRequestBody Body;
        
        public SendSMSReserveRequest() {
        }
        
        public SendSMSReserveRequest(supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class SendSMSReserveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hashValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senderPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string receivePhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string smsContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string reserveDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string reserveTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string userDefine;
        
        public SendSMSReserveRequestBody() {
        }
        
        public SendSMSReserveRequestBody(string smsID, string hashValue, string senderPhone, string receivePhone, string smsContent, string reserveDate, string reserveTime, string userDefine) {
            this.smsID = smsID;
            this.hashValue = hashValue;
            this.senderPhone = senderPhone;
            this.receivePhone = receivePhone;
            this.smsContent = smsContent;
            this.reserveDate = reserveDate;
            this.reserveTime = reserveTime;
            this.userDefine = userDefine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSReserveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSReserveResponse", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveResponseBody Body;
        
        public SendSMSReserveResponse() {
        }
        
        public SendSMSReserveResponse(supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class SendSMSReserveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSReserveResult;
        
        public SendSMSReserveResponseBody() {
        }
        
        public SendSMSReserveResponseBody(string SendSMSReserveResult) {
            this.SendSMSReserveResult = SendSMSReserveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSCallBackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSCallBack", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackRequestBody Body;
        
        public SendSMSCallBackRequest() {
        }
        
        public SendSMSCallBackRequest(supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class SendSMSCallBackRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hashValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senderPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string receivePhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string callbackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string smsContent;
        
        public SendSMSCallBackRequestBody() {
        }
        
        public SendSMSCallBackRequestBody(string smsID, string hashValue, string senderPhone, string receivePhone, string callbackUrl, string smsContent) {
            this.smsID = smsID;
            this.hashValue = hashValue;
            this.senderPhone = senderPhone;
            this.receivePhone = receivePhone;
            this.callbackUrl = callbackUrl;
            this.smsContent = smsContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSCallBackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSCallBackResponse", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackResponseBody Body;
        
        public SendSMSCallBackResponse() {
        }
        
        public SendSMSCallBackResponse(supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class SendSMSCallBackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSCallBackResult;
        
        public SendSMSCallBackResponseBody() {
        }
        
        public SendSMSCallBackResponseBody(string SendSMSCallBackResult) {
            this.SendSMSCallBackResult = SendSMSCallBackResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSCallBackReserveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSCallBackReserve", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveRequestBody Body;
        
        public SendSMSCallBackReserveRequest() {
        }
        
        public SendSMSCallBackReserveRequest(supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class SendSMSCallBackReserveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hashValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senderPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string receivePhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string callbackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string smsContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string reserveDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string reserveTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string userDefine;
        
        public SendSMSCallBackReserveRequestBody() {
        }
        
        public SendSMSCallBackReserveRequestBody(string smsID, string hashValue, string senderPhone, string receivePhone, string callbackUrl, string smsContent, string reserveDate, string reserveTime, string userDefine) {
            this.smsID = smsID;
            this.hashValue = hashValue;
            this.senderPhone = senderPhone;
            this.receivePhone = receivePhone;
            this.callbackUrl = callbackUrl;
            this.smsContent = smsContent;
            this.reserveDate = reserveDate;
            this.reserveTime = reserveTime;
            this.userDefine = userDefine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSCallBackReserveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSCallBackReserveResponse", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveResponseBody Body;
        
        public SendSMSCallBackReserveResponse() {
        }
        
        public SendSMSCallBackReserveResponse(supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class SendSMSCallBackReserveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSCallBackReserveResult;
        
        public SendSMSCallBackReserveResponseBody() {
        }
        
        public SendSMSCallBackReserveResponseBody(string SendSMSCallBackReserveResult) {
            this.SendSMSCallBackReserveResult = SendSMSCallBackReserveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveCancleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveCancle", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.ReserveCancleRequestBody Body;
        
        public ReserveCancleRequest() {
        }
        
        public ReserveCancleRequest(supportsapi.labgenomics.com.ServiceSMS.ReserveCancleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class ReserveCancleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hashValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string searchValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mode;
        
        public ReserveCancleRequestBody() {
        }
        
        public ReserveCancleRequestBody(string smsID, string hashValue, string searchValue, string mode) {
            this.smsID = smsID;
            this.hashValue = hashValue;
            this.searchValue = searchValue;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveCancleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveCancleResponse", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.ReserveCancleResponseBody Body;
        
        public ReserveCancleResponse() {
        }
        
        public ReserveCancleResponse(supportsapi.labgenomics.com.ServiceSMS.ReserveCancleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class ReserveCancleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ReserveCancleResult;
        
        public ReserveCancleResponseBody() {
        }
        
        public ReserveCancleResponseBody(int ReserveCancleResult) {
            this.ReserveCancleResult = ReserveCancleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRemainCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRemainCount", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.GetRemainCountRequestBody Body;
        
        public GetRemainCountRequest() {
        }
        
        public GetRemainCountRequest(supportsapi.labgenomics.com.ServiceSMS.GetRemainCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class GetRemainCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hashValue;
        
        public GetRemainCountRequestBody() {
        }
        
        public GetRemainCountRequestBody(string smsID, string hashValue) {
            this.smsID = smsID;
            this.hashValue = hashValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRemainCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRemainCountResponse", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.GetRemainCountResponseBody Body;
        
        public GetRemainCountResponse() {
        }
        
        public GetRemainCountResponse(supportsapi.labgenomics.com.ServiceSMS.GetRemainCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class GetRemainCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetRemainCountResult;
        
        public GetRemainCountResponseBody() {
        }
        
        public GetRemainCountResponseBody(int GetRemainCountResult) {
            this.GetRemainCountResult = GetRemainCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyLimitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyLimit", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitRequestBody Body;
        
        public GetWeeklyLimitRequest() {
        }
        
        public GetWeeklyLimitRequest(supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class GetWeeklyLimitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hashValue;
        
        public GetWeeklyLimitRequestBody() {
        }
        
        public GetWeeklyLimitRequestBody(string smsID, string hashValue) {
            this.smsID = smsID;
            this.hashValue = hashValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyLimitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyLimitResponse", Namespace="http://webservice.tongkni.co.kr/", Order=0)]
        public supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitResponseBody Body;
        
        public GetWeeklyLimitResponse() {
        }
        
        public GetWeeklyLimitResponse(supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.tongkni.co.kr/")]
    public partial class GetWeeklyLimitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWeeklyLimitResult;
        
        public GetWeeklyLimitResponseBody() {
        }
        
        public GetWeeklyLimitResponseBody(string GetWeeklyLimitResult) {
            this.GetWeeklyLimitResult = GetWeeklyLimitResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSMSSoapChannel : supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSMSSoapClient : System.ServiceModel.ClientBase<supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap>, supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap {
        
        public ServiceSMSSoapClient() {
        }
        
        public ServiceSMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        supportsapi.labgenomics.com.ServiceSMS.SendSMSResponse supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.SendSMS(supportsapi.labgenomics.com.ServiceSMS.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(string smsID, string hashValue, string senderPhone, string receivePhone, string smsContent) {
            supportsapi.labgenomics.com.ServiceSMS.SendSMSRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.SendSMSRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.SendSMSRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            inValue.Body.senderPhone = senderPhone;
            inValue.Body.receivePhone = receivePhone;
            inValue.Body.smsContent = smsContent;
            supportsapi.labgenomics.com.ServiceSMS.SendSMSResponse retVal = ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.SendSMSResponse> supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.SendSMSAsync(supportsapi.labgenomics.com.ServiceSMS.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.SendSMSResponse> SendSMSAsync(string smsID, string hashValue, string senderPhone, string receivePhone, string smsContent) {
            supportsapi.labgenomics.com.ServiceSMS.SendSMSRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.SendSMSRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.SendSMSRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            inValue.Body.senderPhone = senderPhone;
            inValue.Body.receivePhone = receivePhone;
            inValue.Body.smsContent = smsContent;
            return ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveResponse supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.SendSMSReserve(supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveRequest request) {
            return base.Channel.SendSMSReserve(request);
        }
        
        public string SendSMSReserve(string smsID, string hashValue, string senderPhone, string receivePhone, string smsContent, string reserveDate, string reserveTime, string userDefine) {
            supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            inValue.Body.senderPhone = senderPhone;
            inValue.Body.receivePhone = receivePhone;
            inValue.Body.smsContent = smsContent;
            inValue.Body.reserveDate = reserveDate;
            inValue.Body.reserveTime = reserveTime;
            inValue.Body.userDefine = userDefine;
            supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveResponse retVal = ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).SendSMSReserve(inValue);
            return retVal.Body.SendSMSReserveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveResponse> supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.SendSMSReserveAsync(supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveRequest request) {
            return base.Channel.SendSMSReserveAsync(request);
        }
        
        public System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveResponse> SendSMSReserveAsync(string smsID, string hashValue, string senderPhone, string receivePhone, string smsContent, string reserveDate, string reserveTime, string userDefine) {
            supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.SendSMSReserveRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            inValue.Body.senderPhone = senderPhone;
            inValue.Body.receivePhone = receivePhone;
            inValue.Body.smsContent = smsContent;
            inValue.Body.reserveDate = reserveDate;
            inValue.Body.reserveTime = reserveTime;
            inValue.Body.userDefine = userDefine;
            return ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).SendSMSReserveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackResponse supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.SendSMSCallBack(supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackRequest request) {
            return base.Channel.SendSMSCallBack(request);
        }
        
        public string SendSMSCallBack(string smsID, string hashValue, string senderPhone, string receivePhone, string callbackUrl, string smsContent) {
            supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            inValue.Body.senderPhone = senderPhone;
            inValue.Body.receivePhone = receivePhone;
            inValue.Body.callbackUrl = callbackUrl;
            inValue.Body.smsContent = smsContent;
            supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackResponse retVal = ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).SendSMSCallBack(inValue);
            return retVal.Body.SendSMSCallBackResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackResponse> supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.SendSMSCallBackAsync(supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackRequest request) {
            return base.Channel.SendSMSCallBackAsync(request);
        }
        
        public System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackResponse> SendSMSCallBackAsync(string smsID, string hashValue, string senderPhone, string receivePhone, string callbackUrl, string smsContent) {
            supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            inValue.Body.senderPhone = senderPhone;
            inValue.Body.receivePhone = receivePhone;
            inValue.Body.callbackUrl = callbackUrl;
            inValue.Body.smsContent = smsContent;
            return ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).SendSMSCallBackAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveResponse supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.SendSMSCallBackReserve(supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveRequest request) {
            return base.Channel.SendSMSCallBackReserve(request);
        }
        
        public string SendSMSCallBackReserve(string smsID, string hashValue, string senderPhone, string receivePhone, string callbackUrl, string smsContent, string reserveDate, string reserveTime, string userDefine) {
            supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            inValue.Body.senderPhone = senderPhone;
            inValue.Body.receivePhone = receivePhone;
            inValue.Body.callbackUrl = callbackUrl;
            inValue.Body.smsContent = smsContent;
            inValue.Body.reserveDate = reserveDate;
            inValue.Body.reserveTime = reserveTime;
            inValue.Body.userDefine = userDefine;
            supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveResponse retVal = ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).SendSMSCallBackReserve(inValue);
            return retVal.Body.SendSMSCallBackReserveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveResponse> supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.SendSMSCallBackReserveAsync(supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveRequest request) {
            return base.Channel.SendSMSCallBackReserveAsync(request);
        }
        
        public System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveResponse> SendSMSCallBackReserveAsync(string smsID, string hashValue, string senderPhone, string receivePhone, string callbackUrl, string smsContent, string reserveDate, string reserveTime, string userDefine) {
            supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.SendSMSCallBackReserveRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            inValue.Body.senderPhone = senderPhone;
            inValue.Body.receivePhone = receivePhone;
            inValue.Body.callbackUrl = callbackUrl;
            inValue.Body.smsContent = smsContent;
            inValue.Body.reserveDate = reserveDate;
            inValue.Body.reserveTime = reserveTime;
            inValue.Body.userDefine = userDefine;
            return ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).SendSMSCallBackReserveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        supportsapi.labgenomics.com.ServiceSMS.ReserveCancleResponse supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.ReserveCancle(supportsapi.labgenomics.com.ServiceSMS.ReserveCancleRequest request) {
            return base.Channel.ReserveCancle(request);
        }
        
        public int ReserveCancle(string smsID, string hashValue, string searchValue, string mode) {
            supportsapi.labgenomics.com.ServiceSMS.ReserveCancleRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.ReserveCancleRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.ReserveCancleRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            inValue.Body.searchValue = searchValue;
            inValue.Body.mode = mode;
            supportsapi.labgenomics.com.ServiceSMS.ReserveCancleResponse retVal = ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).ReserveCancle(inValue);
            return retVal.Body.ReserveCancleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.ReserveCancleResponse> supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.ReserveCancleAsync(supportsapi.labgenomics.com.ServiceSMS.ReserveCancleRequest request) {
            return base.Channel.ReserveCancleAsync(request);
        }
        
        public System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.ReserveCancleResponse> ReserveCancleAsync(string smsID, string hashValue, string searchValue, string mode) {
            supportsapi.labgenomics.com.ServiceSMS.ReserveCancleRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.ReserveCancleRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.ReserveCancleRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            inValue.Body.searchValue = searchValue;
            inValue.Body.mode = mode;
            return ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).ReserveCancleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        supportsapi.labgenomics.com.ServiceSMS.GetRemainCountResponse supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.GetRemainCount(supportsapi.labgenomics.com.ServiceSMS.GetRemainCountRequest request) {
            return base.Channel.GetRemainCount(request);
        }
        
        public int GetRemainCount(string smsID, string hashValue) {
            supportsapi.labgenomics.com.ServiceSMS.GetRemainCountRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.GetRemainCountRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.GetRemainCountRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            supportsapi.labgenomics.com.ServiceSMS.GetRemainCountResponse retVal = ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).GetRemainCount(inValue);
            return retVal.Body.GetRemainCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.GetRemainCountResponse> supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.GetRemainCountAsync(supportsapi.labgenomics.com.ServiceSMS.GetRemainCountRequest request) {
            return base.Channel.GetRemainCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.GetRemainCountResponse> GetRemainCountAsync(string smsID, string hashValue) {
            supportsapi.labgenomics.com.ServiceSMS.GetRemainCountRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.GetRemainCountRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.GetRemainCountRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            return ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).GetRemainCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitResponse supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.GetWeeklyLimit(supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitRequest request) {
            return base.Channel.GetWeeklyLimit(request);
        }
        
        public string GetWeeklyLimit(string smsID, string hashValue) {
            supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitResponse retVal = ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).GetWeeklyLimit(inValue);
            return retVal.Body.GetWeeklyLimitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitResponse> supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap.GetWeeklyLimitAsync(supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitRequest request) {
            return base.Channel.GetWeeklyLimitAsync(request);
        }
        
        public System.Threading.Tasks.Task<supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitResponse> GetWeeklyLimitAsync(string smsID, string hashValue) {
            supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitRequest inValue = new supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitRequest();
            inValue.Body = new supportsapi.labgenomics.com.ServiceSMS.GetWeeklyLimitRequestBody();
            inValue.Body.smsID = smsID;
            inValue.Body.hashValue = hashValue;
            return ((supportsapi.labgenomics.com.ServiceSMS.ServiceSMSSoap)(this)).GetWeeklyLimitAsync(inValue);
        }
    }
}
