name: Support-api

on:
  push:
    branches:  "main"

jobs:

  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build a Visual Studio project or solution using MSBuild
      run:  msbuild -p:Configuration=Release -p:DeployOnBuild=true -t:restore,build -p:RestorePackagesConfig=true

    -  name: Setup .NET SDK
       uses: actions/setup-dotnet@v2
       with:
        dotnet-version: '4.6.1' 
  
    - name: Execute Windows batch command
      run: \supportsapi.labgenomics.com\supportsapi.labgenomics.com\obj\Release\Package\PackageTmp\web.config

    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: MSIX Package
    #     path: ${{ env.Wap_Project_Directory }}\AppPackages
