name: Support-api

on:
  push:
    branches:  "main"

jobs:
  build:
    runs-on: windows-2019 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1  

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION }}    
        
    - name: Build using MSBuild
      run:  msbuild -p:Configuration=Release -p:DeployOnBuild=true -t:restore,build -p:RestorePackagesConfig=true

    - name: Execute Windows batch command
      run:   del " ${{env.GITHUB_WORKSPACE}}\..\supportsapi.labgenomics.com\obj\Release\Package\PackageTmp\web.config"

    - name: Set up Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: ${{ github.workspace }}\supportsapi.labgenomics.com\obj\Release\Package\PackageTmp


  deploy:
    needs: build
    runs-on: windows-2019
    
    steps:  
     - name: Checkout repository
       uses: actions/checkout@v2
       
     - name: Download Artifact
       uses: actions/download-artifact@v2
       with:
         name: build-output
         path: ${{env.GITHUB_WORKSPACE}}\supportsapi.labgenomics.com\obj\Release\Package\PackageTmp

     - name: Upload ftp
       run: |
         $webClient = New-Object System.Net.WebClient
         $webClient.Credentials = New-Object System.Net.NetworkCredential('${{ secrets.FTP_USERNAME }}', '${{ secrets.FTP_PASSWORD }}')

         Get-ChildItem -Path "${{ env.GITHUB_WORKSPACE }}\supportsapi.labgenomics.com\obj\Release\Package\PackageTmp" -Recurse | ForEach-Object {
             $remotePath = "/supportsapi.labgenomics.com/" + $_.FullName.Substring(${{ env.GITHUB_WORKSPACE.Length + 1 }}).Replace("\", "/")
             Write-Host "Uploading $($_.FullName) to ftp://${{ secrets.FTP_SERVER }}$($remotePath)"
             $webClient.UploadFile("ftp://${{ secrets.FTP_SERVER }}$($remotePath)", "STOR", $_.FullName)
         }
